### ISSUE TITLE
Remove correct python for other versions

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/python-and-julia#1]
https://github.com/abelsiqueira/python-and-julia/blob/20a54b2771caa8fbdd2c17cdcdafdc6c895066fb/Dockerfile#L43

**Comment by muzakkirsaifi123** [comment]
Hi, @abelsiqueira I want to resolve this issue..

**Comment by abelsiqueira** [comment]
Hi @muzakkirsaifi123, I'm just finishing this up right now. Thanks for making yourself available, let me know if you find other issues.

**Comment by muzakkirsaifi123** [comment]
sure.
