### ISSUE TITLE
Newer Ubuntu

### ISSUE THREAD

**Issue by rudolfbyker** [abelsiqueira/python-and-julia#4]
Ubuntu 21 is EOL, so `apt install` no longer works on this image if we need something extra. It's probably a good idea to use an LTS version next time.

**Comment by rudolfbyker** [comment]
Just changing the FROM line in the Dockerfile to use Ubuntu 22.04 seems to fix this for me.

**Comment by abelsiqueira** [comment]
Hi Rudolf, thanks for opening this issue. Glad to see people using the
image. Indeed it should be just a change to the from. Do you mind opening a
pull request?

**Comment by rudolfbyker** [comment]
Done :)
